// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSM0S-THa8GbT1t8gWW1BApKh6dlGtZiw',
    appId: '1:4316345143:web:5f7c9caaef3f107837a0b2',
    messagingSenderId: '4316345143',
    projectId: 'protective-link-manager',
    authDomain: 'protective-link-manager.firebaseapp.com',
    storageBucket: 'protective-link-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vjk7E8L14p5d9A12xVqBw79bEw34Pik',
    appId: '1:4316345143:android:cf056bd4211173ef37a0b2',
    messagingSenderId: '4316345143',
    projectId: 'protective-link-manager',
    storageBucket: 'protective-link-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm8hZ2yP11msW2NNKGb9Tkdrm11Xb8StY',
    appId: '1:4316345143:ios:d7581907bdc13a0a37a0b2',
    messagingSenderId: '4316345143',
    projectId: 'protective-link-manager',
    storageBucket: 'protective-link-manager.appspot.com',
    iosBundleId: 'com.example.flutterBleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm8hZ2yP11msW2NNKGb9Tkdrm11Xb8StY',
    appId: '1:4316345143:ios:d7581907bdc13a0a37a0b2',
    messagingSenderId: '4316345143',
    projectId: 'protective-link-manager',
    storageBucket: 'protective-link-manager.appspot.com',
    iosBundleId: 'com.example.flutterBleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSM0S-THa8GbT1t8gWW1BApKh6dlGtZiw',
    appId: '1:4316345143:web:1b49e25276caa18a37a0b2',
    messagingSenderId: '4316345143',
    projectId: 'protective-link-manager',
    authDomain: 'protective-link-manager.firebaseapp.com',
    storageBucket: 'protective-link-manager.appspot.com',
  );
}
